# Generated by Django 2.2.5 on 2019-09-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imame',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.TextField(default='', max_length=120),
        ),
    ]
