# Generated by Django 2.2.5 on 2019-09-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190918_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imame',
            new_name='image',
        ),
    ]
